version: '3.8'

services:
  apple-inventory-frontend:
    build: .
    container_name: apple-inventory-fe_ctr
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL:-http://localhost:1337}
    stdin_open: true
    ports:
     - 3000:3000
